// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfhcwvarwxnhjebtoume.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmaGN3dmFyd3huaGplYnRvdW1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyODI1NDQsImV4cCI6MjA2Nzg1ODU0NH0.CUFgl6bewRmZ4md2605ep19Ht0JhpcxXf79Ob4cbvBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});